
#Do not edit this file, without updating
#  alkNC-aws_cloud1 set up Terraform config.txt reference.

#This key will be used only on freshly deployed EC2 instances.
#It shall be disabled on a very early stage of any postinstall precodure,
#  and substituted by a personalized SysAdmin key,
#  out of the scope of Terraform orchestration.

#2DO: instead of hardcoding the key, take it from the stored location

resource "aws_key_pair" "alkNC-deployer-key" {
  key_name   = "alkNC-deployer-key"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWJPAWEJKF9hL/Qvhk4mctLQq0LYeEoTLKKNHiBk6Bs9XfTNUM1c0c03Ap1ZkQH/Um3PgJuwg5OSHsGQiESJpQ5HJDKF9s9ZpXnVICmZxaFFXz/F3OXG/e+6FhBdSo/eH2Y83hYLC3SFHI2N9HvfyrEoqPHb634kmPZWHsqK+Ggh/05gXPk0y/Dg0RbF1L+8nOQZoUEIwe0LeZOBs5S5+K6etdt0PhaZABsa4GT3QdFfPJRzVIebo7MkuHLCc0yw34IgoSChRs0XuEM87uOHbwCHMSe7rjdl5PdhhxIb11bLMH53ellmr/kwEUgDQMcz+37pWm//6MC7Z2g9pRQl1B alkNC-deployer@aws_2022-04-04T200847"
  tags = {
    Name = "alkNC-deployer-key"
  }
}

