# This is a placeholder for AWS Cloud space for ${PROJECT}.
# Since the value of some of this parameters is a secret
#   Terraform should take them from environment variables
#   so they remain volatile,
#   istead of being stored in a plain file.

#Do not edit this file, without updating
#  alkNC-aws_cloud1 set up Terraform config.txt reference.

provider "aws" {
#  access_key = "XXXX"
#  secret_key = "YYYYY"
#  region     = "us-west-2"
}

