
#Do not edit this file, without updating
#  alkNC-aws_cloud1 set up Terraform config.txt reference.

## Main VPC for "Alk-Netcracker Test Case" in AWS
resource "aws_vpc" "alkNC-vpc" {
    cidr_block = "10.200.0.0/20"
    enable_dns_hostnames = true
    enable_dns_support   = true
    instance_tenancy     = "default"
    tags = {
        Name = "alkNC-vpc"
    }
}

#2DO: If the real domain name is coded into aws_route53_zone resource name
#  sustitute "." characters with something that won't spook Terraform.
#  Like "us-east-1.alkNC.i" -> "us-east-1-alkNC-i".

#resource "aws_route53_zone" "aws-us-east-1-alkNC-i-r53" {
resource "aws_route53_zone" "alkNC-local-r53" {
    name       = "local"
    comment    = "Private Hosted Zone for Alk-Netcracker Test Case Project"
    vpc {
        vpc_id = "${aws_vpc.alkNC-vpc.id}"
    }
    tags = {
        Name = "alkNC-local-r53"
    }
}

## Default DHCP options set
resource "aws_vpc_dhcp_options" "alkNC-dhcpopt" {
  domain_name          = "local"
  domain_name_servers  = ["AmazonProvidedDNS"]
  tags = {
    Name = "alkNC-dhcpopt"
  }
}
resource "aws_vpc_dhcp_options_association" "alkNC-dhcpopt-assoc" {
  vpc_id          = "${aws_vpc.alkNC-vpc.id}"
  dhcp_options_id = "${aws_vpc_dhcp_options.alkNC-dhcpopt.id}"
}


output "alkNC-vpc" {
  value = "${aws_vpc.alkNC-vpc.id}"
}
output "alkNC-vpc_cidr" {
  value = "${aws_vpc.alkNC-vpc.cidr_block}"
}
output "alkNC-local-r53" {
  value = "${aws_route53_zone.alkNC-local-r53.id}"
}

