---
- hosts: frontend
  remote_user: centos
  become: yes
  vars:
    ssh_private_key_file: ../.secrets/alkNC-deployer-key_2022-04-04T200847

  tasks:

#    - name: test connection
#      ping:

#2DO: Is there a generci way to call a package installation?
#  so dnf is called on CentOS, and apt is called on Ubuntu...
    - name: Ensure Nginx is installed
      dnf:
        name: nginx
        state: latest

#Not really, defaut installation of Nginx in CentOS
#  already has a config one nice enough
#    - name: Establish basic configuration for Nginx
#      copy:
#        dest: "/etc/nginx/conf.d/default.conf"
#        content: |
#          server {
#            listen   80 default_server;
#            server_tokens off;
#            location / {
#              root   /srv/www;
#              index  index.html index.htm;
#              allow 127.0.0.1;
#              allow 10.0.0.0/8;
#              deny all;
#            }
#          }
#      notify:
#        - restart nginx

    - name: Create a config library for Nginx reverse proxy
      copy:
        dest: "/etc/nginx/conf.d/rproxy-options.conflib"
        content: |
          # http://kovyrin.net/2006/04/17/typical-nginx-configurations/
          proxy_set_header   Host             $host;
          proxy_set_header   X-Real-IP        $remote_addr;
          proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
          proxy_max_temp_file_size 0;
          
          client_max_body_size       10m;
          client_body_buffer_size    128k;
          
          proxy_connect_timeout      90;
          proxy_send_timeout         90;
          proxy_read_timeout         180;

    - name: Create document-root for Nginx
      file:
        path: /srv/www
        state: directory
        owner: nginx
        group: nginx
        mode: 0770

    - name: Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a config library for Nginx reverse proxy
      copy:
        dest: "/etc/nginx/conf.d/rproxy-netdata.conf"
        content: |
          server {
            listen 80;
            server_name {{ ansible_host }};
          #  server_name _;
            location / {
              proxy_pass http://10.200.4.8:19999/;
              include /etc/nginx/conf.d/rproxy-options.conflib;
            }
          }
      notify:
        - restart nginx

#2DO: Use file copy facility intead of setting the contents inline.
#2DO: fix the upstream's URL, don't hardcode a IP address.
#  Note: Can't just use "u21.local"
#    becouse if it's not resolvable, Nginx won't start.

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes


